#!/usr/bin/env ruby

# Always look in the lib directory of this gem
# first when searching the load path
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'boleto/cli'

exit Boleto::Cli.new(ARGV).execute
